version: '3'
services:
  app_back:
    build: .
    container_name: app_back
    volumes:
      - ./back:/var/www/backend
    ports:
      - 8000:8000
    tty: true

  app_front:
    image: node:18.16
    container_name: app_front
    working_dir: /var/www/frontend
    volumes:
      - ./front:/var/www/frontend
    ports:
      - 4445:3000
    tty: true

  db:
    image: mysql:8.0-debian
    container_name: mysql8
    working_dir: /data
    volumes:
      - ./db:/data
    ports:
      - 2021:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password